name: "Minitest Report"
description: "A GitHub Action that reports Minitest failure."
branding:
  icon: alert-triangle
  color: red
author: "davegudge"
inputs:
  token:
    description: "Github token"
    required: true
  json-path:
    description: "JSON File path"
    required: true
  title:
    description: "Title"
    default: "# :x: Minitest failure"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
